namespace Airslip.Analytics.Core.Enums;

public enum AccountBalanceType
{
    CLOSING_AVAILABLE, 
    CLOSING_BOOKED, 
    CLOSING_CLEARED, 
    EXPECTED, 
    FORWARD_AVAILABLE, 
    INFORMATION, 
    INTERIM_AVAILABLE, 
    INTERIM_BOOKED, 
    INTERIM_CLEARED, 
    OPENING_AVAILABLE, 
    OPENING_BOOKED, 
    OPENING_CLEARED, 
    PREVIOUSLY_CLOSED_BOOKED, 
    AUTHORISED, 
    OTHER, 
    UNKNOWN
}