// <auto-generated />
using System;
using Airslip.Analytics.Services.SqlServer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Airslip.Analytics.Services.SqlServer.Migrations
{
    [DbContext(typeof(SqlServerContext))]
    [Migration("20220127204557_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Airslip.Analytics.Core.Entities.Bank", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuditInformationId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("DataSource")
                        .HasColumnType("int");

                    b.Property<int>("EntityStatus")
                        .HasColumnType("int");

                    b.Property<string>("EnvironmentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TimeStamp")
                        .HasColumnType("bigint");

                    b.Property<string>("TradingName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_Banks_Id");

                    b.HasIndex("AuditInformationId");

                    b.ToTable("Banks", (string)null);
                });

            modelBuilder.Entity("Airslip.Analytics.Core.Entities.BankAccount", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AccountStatus")
                        .HasColumnType("int");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AirslipUserType")
                        .HasColumnType("int");

                    b.Property<string>("AuditInformationId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BankId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DataSource")
                        .HasColumnType("int");

                    b.Property<string>("EntityId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EntityStatus")
                        .HasColumnType("int");

                    b.Property<string>("InstitutionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastCardDigits")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SortCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TimeStamp")
                        .HasColumnType("bigint");

                    b.Property<string>("UsageType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_BankAccounts_Id");

                    b.HasIndex("AuditInformationId");

                    b.ToTable("BankAccounts", (string)null);
                });

            modelBuilder.Entity("Airslip.Analytics.Core.Entities.BankAccountBalance", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AirslipUserType")
                        .HasColumnType("int");

                    b.Property<string>("AuditInformationId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("Balance")
                        .HasColumnType("bigint");

                    b.Property<int>("BalanceStatus")
                        .HasColumnType("int");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DataSource")
                        .HasColumnType("int");

                    b.Property<string>("EntityId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EntityStatus")
                        .HasColumnType("int");

                    b.Property<long>("TimeStamp")
                        .HasColumnType("bigint");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_BankAccountBalances_Id");

                    b.HasIndex("AuditInformationId");

                    b.ToTable("BankAccountBalances", (string)null);
                });

            modelBuilder.Entity("Airslip.Analytics.Core.Entities.BankAccountBalanceCreditLine", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccountBalanceDetailId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Balance")
                        .HasColumnType("bigint");

                    b.Property<int>("BalanceStatus")
                        .HasColumnType("int");

                    b.Property<string>("BankAccountBalanceDetailId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CreditLineType")
                        .HasColumnType("int");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_BankAccountBalanceCreditLines_Id");

                    b.HasIndex("BankAccountBalanceDetailId");

                    b.ToTable("BankAccountBalanceCreditLines", (string)null);
                });

            modelBuilder.Entity("Airslip.Analytics.Core.Entities.BankAccountBalanceDetail", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccountBalanceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Balance")
                        .HasColumnType("bigint");

                    b.Property<int>("BalanceStatus")
                        .HasColumnType("int");

                    b.Property<int>("BalanceType")
                        .HasColumnType("int");

                    b.Property<string>("BankAccountBalanceId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("CreditLineIncluded")
                        .HasColumnType("bit");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateTime")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_BankAccountBalanceDetails_Id");

                    b.HasIndex("BankAccountBalanceId");

                    b.ToTable("BankAccountBalanceDetails", (string)null);
                });

            modelBuilder.Entity("Airslip.Analytics.Core.Entities.BankAccountBalanceSnapshot", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AirslipUserType")
                        .HasColumnType("int");

                    b.Property<long>("Balance")
                        .HasColumnType("bigint");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TimeStamp")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK_BankAccountBalanceSnapshots_Id");

                    b.ToTable("BankAccountBalanceSnapshots", (string)null);
                });

            modelBuilder.Entity("Airslip.Analytics.Core.Entities.BankAccountBalanceSummary", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("dbo.getId()");

                    b.Property<string>("AccountId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AirslipUserType")
                        .HasColumnType("int");

                    b.Property<long>("Balance")
                        .HasColumnType("bigint");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Movement")
                        .HasColumnType("float");

                    b.Property<long>("TimeStamp")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK_BankAccountBalanceSummaries_Id");

                    b.ToTable("BankAccountBalanceSummaries", (string)null);
                });

            modelBuilder.Entity("Airslip.Analytics.Core.Entities.BankBusinessBalance", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("dbo.getId()");

                    b.Property<int>("AirslipUserType")
                        .HasColumnType("int");

                    b.Property<long>("Balance")
                        .HasColumnType("bigint");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Movement")
                        .HasColumnType("float");

                    b.Property<long>("TimeStamp")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK_BankBusinessBalances_Id");

                    b.ToTable("BankBusinessBalances", (string)null);
                });

            modelBuilder.Entity("Airslip.Analytics.Core.Entities.BankBusinessBalanceSnapshot", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AirslipUserType")
                        .HasColumnType("int");

                    b.Property<long>("Balance")
                        .HasColumnType("bigint");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TimeStamp")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK_BankBusinessBalanceSnapshots_Id");

                    b.ToTable("BankBusinessBalanceSnapshots", (string)null);
                });

            modelBuilder.Entity("Airslip.Analytics.Core.Entities.BankCountryCode", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BankId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("BankId");

                    b.ToTable("BankCountryCode");
                });

            modelBuilder.Entity("Airslip.Analytics.Core.Entities.BankSyncRequest", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AccountType")
                        .HasColumnType("int");

                    b.Property<int>("AirslipUserType")
                        .HasColumnType("int");

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuditInformationId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("DataSource")
                        .HasColumnType("int");

                    b.Property<string>("EntityId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EntityStatus")
                        .HasColumnType("int");

                    b.Property<string>("FromDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastCardDigits")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecordCount")
                        .HasColumnType("int");

                    b.Property<int>("SyncStatus")
                        .HasColumnType("int");

                    b.Property<long>("TimeStamp")
                        .HasColumnType("bigint");

                    b.Property<string>("TracingId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsageType")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_BankSyncRequests_Id");

                    b.HasIndex("AuditInformationId");

                    b.ToTable("BankSyncRequests", (string)null);
                });

            modelBuilder.Entity("Airslip.Analytics.Core.Entities.BankTransaction", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressLine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AirslipUserType")
                        .HasColumnType("int");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint");

                    b.Property<string>("AuditInformationId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<long?>("AuthorisedDate")
                        .HasColumnType("bigint");

                    b.Property<string>("BankId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankTransactionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("CapturedDate")
                        .HasColumnType("bigint");

                    b.Property<string>("CurrencyCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DataSource")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EntityStatus")
                        .HasColumnType("int");

                    b.Property<string>("IsoFamilyCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastCardDigits")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProprietaryCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TimeStamp")
                        .HasColumnType("bigint");

                    b.Property<string>("TransactionHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionIdentifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_BankTransactions_Id");

                    b.HasIndex("AuditInformationId");

                    b.ToTable("BankTransactions", (string)null);
                });

            modelBuilder.Entity("Airslip.Analytics.Core.Entities.CountryCode", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id")
                        .HasName("PK_CountryCodes_Id");

                    b.ToTable("CountryCodes", (string)null);
                });

            modelBuilder.Entity("Airslip.Analytics.Core.Entities.MerchantProduct", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dimensions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("DiscountAmount")
                        .HasColumnType("bigint");

                    b.Property<string>("Ean")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManualUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MerchantTransactionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ModelNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParentTransactionProductId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("Price")
                        .HasColumnType("bigint");

                    b.Property<long?>("PriceIncTax")
                        .HasColumnType("bigint");

                    b.Property<string>("ProductCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductStatus")
                        .HasColumnType("int");

                    b.Property<double?>("Quantity")
                        .HasColumnType("float");

                    b.Property<string>("Sku")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("TaxPercent")
                        .HasColumnType("float");

                    b.Property<long?>("TaxValue")
                        .HasColumnType("bigint");

                    b.Property<long?>("TaxValueAfterDiscount")
                        .HasColumnType("bigint");

                    b.Property<long?>("TotalPrice")
                        .HasColumnType("bigint");

                    b.Property<string>("TransactionProductId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Upc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VariantId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("WarrantyExpiryDateTime")
                        .HasColumnType("bigint");

                    b.Property<double?>("Weight")
                        .HasColumnType("float");

                    b.Property<string>("WeightUnit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_MerchantProducts_Id");

                    b.HasIndex("MerchantTransactionId");

                    b.ToTable("MerchantProducts", (string)null);
                });

            modelBuilder.Entity("Airslip.Analytics.Core.Entities.MerchantRefund", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("Fee")
                        .HasColumnType("bigint");

                    b.Property<string>("MerchantTransactionId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ModifiedTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("Shipping")
                        .HasColumnType("bigint");

                    b.Property<long?>("Tax")
                        .HasColumnType("bigint");

                    b.Property<long?>("Total")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("PK_MerchantRefunds_Id");

                    b.HasIndex("MerchantTransactionId");

                    b.ToTable("MerchantRefunds", (string)null);
                });

            modelBuilder.Entity("Airslip.Analytics.Core.Entities.MerchantRefundItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MerchantRefundId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProductId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Qty")
                        .HasColumnType("float");

                    b.Property<long?>("Refund")
                        .HasColumnType("bigint");

                    b.Property<string>("TransactionProductId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VariantId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_MerchantRefundItems_Id");

                    b.HasIndex("MerchantRefundId");

                    b.ToTable("MerchantRefundItems", (string)null);
                });

            modelBuilder.Entity("Airslip.Analytics.Core.Entities.MerchantTransaction", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AirslipUserType")
                        .HasColumnType("int");

                    b.Property<string>("AuditInformationId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BankStatementDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankStatementTransactionIdentifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrencyCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DataSource")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Datetime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Day")
                        .HasColumnType("int");

                    b.Property<string>("EntityId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EntityStatus")
                        .HasColumnType("int");

                    b.Property<string>("InternalId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Month")
                        .HasColumnType("int");

                    b.Property<string>("Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("OnlinePurchase")
                        .HasColumnType("bit");

                    b.Property<string>("OperatorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefundCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ServiceCharge")
                        .HasColumnType("bigint");

                    b.Property<string>("Source")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Store")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StoreAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StoreLocationId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("Subtotal")
                        .HasColumnType("bigint");

                    b.Property<string>("Till")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Time")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TimeStamp")
                        .HasColumnType("bigint");

                    b.Property<long?>("Total")
                        .HasColumnType("bigint");

                    b.Property<string>("TrackingId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_MerchantTransactions_Id");

                    b.HasIndex("AuditInformationId");

                    b.ToTable("MerchantTransactions", (string)null);
                });

            modelBuilder.Entity("Airslip.Common.Repository.Types.Entities.BasicAuditInformation", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedByUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedByUserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_AuditInformation_Id");

                    b.ToTable("AuditInformation", (string)null);
                });

            modelBuilder.Entity("Airslip.Analytics.Core.Entities.Bank", b =>
                {
                    b.HasOne("Airslip.Common.Repository.Types.Entities.BasicAuditInformation", "AuditInformation")
                        .WithMany()
                        .HasForeignKey("AuditInformationId");

                    b.Navigation("AuditInformation");
                });

            modelBuilder.Entity("Airslip.Analytics.Core.Entities.BankAccount", b =>
                {
                    b.HasOne("Airslip.Common.Repository.Types.Entities.BasicAuditInformation", "AuditInformation")
                        .WithMany()
                        .HasForeignKey("AuditInformationId");

                    b.Navigation("AuditInformation");
                });

            modelBuilder.Entity("Airslip.Analytics.Core.Entities.BankAccountBalance", b =>
                {
                    b.HasOne("Airslip.Common.Repository.Types.Entities.BasicAuditInformation", "AuditInformation")
                        .WithMany()
                        .HasForeignKey("AuditInformationId");

                    b.Navigation("AuditInformation");
                });

            modelBuilder.Entity("Airslip.Analytics.Core.Entities.BankAccountBalanceCreditLine", b =>
                {
                    b.HasOne("Airslip.Analytics.Core.Entities.BankAccountBalanceDetail", null)
                        .WithMany("CreditLines")
                        .HasForeignKey("BankAccountBalanceDetailId");
                });

            modelBuilder.Entity("Airslip.Analytics.Core.Entities.BankAccountBalanceDetail", b =>
                {
                    b.HasOne("Airslip.Analytics.Core.Entities.BankAccountBalance", null)
                        .WithMany("Details")
                        .HasForeignKey("BankAccountBalanceId");
                });

            modelBuilder.Entity("Airslip.Analytics.Core.Entities.BankCountryCode", b =>
                {
                    b.HasOne("Airslip.Analytics.Core.Entities.Bank", null)
                        .WithMany("CountryCodes")
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Airslip.Analytics.Core.Entities.BankSyncRequest", b =>
                {
                    b.HasOne("Airslip.Common.Repository.Types.Entities.BasicAuditInformation", "AuditInformation")
                        .WithMany()
                        .HasForeignKey("AuditInformationId");

                    b.Navigation("AuditInformation");
                });

            modelBuilder.Entity("Airslip.Analytics.Core.Entities.BankTransaction", b =>
                {
                    b.HasOne("Airslip.Common.Repository.Types.Entities.BasicAuditInformation", "AuditInformation")
                        .WithMany()
                        .HasForeignKey("AuditInformationId");

                    b.Navigation("AuditInformation");
                });

            modelBuilder.Entity("Airslip.Analytics.Core.Entities.MerchantProduct", b =>
                {
                    b.HasOne("Airslip.Analytics.Core.Entities.MerchantTransaction", null)
                        .WithMany("Products")
                        .HasForeignKey("MerchantTransactionId");
                });

            modelBuilder.Entity("Airslip.Analytics.Core.Entities.MerchantRefund", b =>
                {
                    b.HasOne("Airslip.Analytics.Core.Entities.MerchantTransaction", null)
                        .WithMany("Refunds")
                        .HasForeignKey("MerchantTransactionId");
                });

            modelBuilder.Entity("Airslip.Analytics.Core.Entities.MerchantRefundItem", b =>
                {
                    b.HasOne("Airslip.Analytics.Core.Entities.MerchantRefund", null)
                        .WithMany("Items")
                        .HasForeignKey("MerchantRefundId");
                });

            modelBuilder.Entity("Airslip.Analytics.Core.Entities.MerchantTransaction", b =>
                {
                    b.HasOne("Airslip.Common.Repository.Types.Entities.BasicAuditInformation", "AuditInformation")
                        .WithMany()
                        .HasForeignKey("AuditInformationId");

                    b.Navigation("AuditInformation");
                });

            modelBuilder.Entity("Airslip.Analytics.Core.Entities.Bank", b =>
                {
                    b.Navigation("CountryCodes");
                });

            modelBuilder.Entity("Airslip.Analytics.Core.Entities.BankAccountBalance", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("Airslip.Analytics.Core.Entities.BankAccountBalanceDetail", b =>
                {
                    b.Navigation("CreditLines");
                });

            modelBuilder.Entity("Airslip.Analytics.Core.Entities.MerchantRefund", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Airslip.Analytics.Core.Entities.MerchantTransaction", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("Refunds");
                });
#pragma warning restore 612, 618
        }
    }
}
