// <auto-generated />
using System;
using Airslip.Analytics.Services.SqlServer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Airslip.Analytics.Services.SqlServer.Migrations
{
    [DbContext(typeof(SqlServerContext))]
    partial class SqlServerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Airslip.Analytics.Core.Entities.Account", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AccountStatus")
                        .HasColumnType("int");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AirslipUserType")
                        .HasColumnType("int");

                    b.Property<string>("AuditInformationId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BankId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DataSource")
                        .HasColumnType("int");

                    b.Property<string>("EntityId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EntityStatus")
                        .HasColumnType("int");

                    b.Property<string>("InstitutionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastCardDigits")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SortCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TimeStamp")
                        .HasColumnType("bigint");

                    b.Property<string>("UsageType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_Accounts_Id");

                    b.HasIndex("AuditInformationId");

                    b.ToTable("Accounts", (string)null);
                });

            modelBuilder.Entity("Airslip.Analytics.Core.Entities.AccountBalance", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AirslipUserType")
                        .HasColumnType("int");

                    b.Property<string>("AuditInformationId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("Balance")
                        .HasColumnType("bigint");

                    b.Property<int>("BalanceStatus")
                        .HasColumnType("int");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DataSource")
                        .HasColumnType("int");

                    b.Property<string>("EntityId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EntityStatus")
                        .HasColumnType("int");

                    b.Property<long>("TimeStamp")
                        .HasColumnType("bigint");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_AccountBalances_Id");

                    b.HasIndex("AuditInformationId");

                    b.ToTable("AccountBalances", (string)null);
                });

            modelBuilder.Entity("Airslip.Analytics.Core.Entities.AccountBalanceCreditLine", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccountBalanceDetailId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("Balance")
                        .HasColumnType("bigint");

                    b.Property<int>("BalanceStatus")
                        .HasColumnType("int");

                    b.Property<int>("CreditLineType")
                        .HasColumnType("int");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_AccountBalanceCreditLines_Id");

                    b.HasIndex("AccountBalanceDetailId");

                    b.ToTable("AccountBalanceCreditLines", (string)null);
                });

            modelBuilder.Entity("Airslip.Analytics.Core.Entities.AccountBalanceDetail", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccountBalanceId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("Balance")
                        .HasColumnType("bigint");

                    b.Property<int>("BalanceStatus")
                        .HasColumnType("int");

                    b.Property<int>("BalanceType")
                        .HasColumnType("int");

                    b.Property<bool>("CreditLineIncluded")
                        .HasColumnType("bit");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateTime")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_AccountBalanceDetails_Id");

                    b.HasIndex("AccountBalanceId");

                    b.ToTable("AccountBalanceDetails", (string)null);
                });

            modelBuilder.Entity("Airslip.Analytics.Core.Entities.AccountBalanceSnapshot", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AirslipUserType")
                        .HasColumnType("int");

                    b.Property<long>("Balance")
                        .HasColumnType("bigint");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TimeStamp")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK_AccountBalanceSnapshots_Id");

                    b.ToTable("AccountBalanceSnapshots", (string)null);
                });

            modelBuilder.Entity("Airslip.Analytics.Core.Entities.AccountBalanceSummary", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("dbo.getId()");

                    b.Property<string>("AccountId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AirslipUserType")
                        .HasColumnType("int");

                    b.Property<long>("Balance")
                        .HasColumnType("bigint");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Movement")
                        .HasColumnType("float");

                    b.Property<long>("TimeStamp")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK_AccountBalanceSummaries_Id");

                    b.ToTable("AccountBalanceSummaries", (string)null);
                });

            modelBuilder.Entity("Airslip.Analytics.Core.Entities.Bank", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuditInformationId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("DataSource")
                        .HasColumnType("int");

                    b.Property<int>("EntityStatus")
                        .HasColumnType("int");

                    b.Property<string>("EnvironmentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TimeStamp")
                        .HasColumnType("bigint");

                    b.Property<string>("TradingName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_Banks_Id");

                    b.HasIndex("AuditInformationId");

                    b.ToTable("Banks", (string)null);
                });

            modelBuilder.Entity("Airslip.Analytics.Core.Entities.BankCountryCode", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BankId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("BankId");

                    b.ToTable("BankCountryCode");
                });

            modelBuilder.Entity("Airslip.Analytics.Core.Entities.BusinessBalance", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("dbo.getId()");

                    b.Property<int>("AirslipUserType")
                        .HasColumnType("int");

                    b.Property<long>("Balance")
                        .HasColumnType("bigint");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Movement")
                        .HasColumnType("float");

                    b.Property<long>("TimeStamp")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK_BusinessBalances_Id");

                    b.ToTable("BusinessBalances", (string)null);
                });

            modelBuilder.Entity("Airslip.Analytics.Core.Entities.BusinessBalanceSnapshot", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AirslipUserType")
                        .HasColumnType("int");

                    b.Property<long>("Balance")
                        .HasColumnType("bigint");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TimeStamp")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK_BusinessBalanceSnapshots_Id");

                    b.ToTable("BusinessBalanceSnapshots", (string)null);
                });

            modelBuilder.Entity("Airslip.Analytics.Core.Entities.CountryCode", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id")
                        .HasName("PK_CountryCodes_Id");

                    b.ToTable("CountryCodes", (string)null);
                });

            modelBuilder.Entity("Airslip.Analytics.Core.Entities.SyncRequest", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AccountType")
                        .HasColumnType("int");

                    b.Property<int>("AirslipUserType")
                        .HasColumnType("int");

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AuditInformationId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("DataSource")
                        .HasColumnType("int");

                    b.Property<string>("EntityId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EntityStatus")
                        .HasColumnType("int");

                    b.Property<string>("FromDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastCardDigits")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecordCount")
                        .HasColumnType("int");

                    b.Property<int>("SyncStatus")
                        .HasColumnType("int");

                    b.Property<long>("TimeStamp")
                        .HasColumnType("bigint");

                    b.Property<string>("TracingId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsageType")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_SyncRequests_Id");

                    b.HasIndex("AuditInformationId");

                    b.ToTable("SyncRequests", (string)null);
                });

            modelBuilder.Entity("Airslip.Analytics.Core.Entities.Transaction", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressLine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AirslipUserType")
                        .HasColumnType("int");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint");

                    b.Property<string>("AuditInformationId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<long?>("AuthorisedDate")
                        .HasColumnType("bigint");

                    b.Property<string>("BankId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankTransactionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("CapturedDate")
                        .HasColumnType("bigint");

                    b.Property<string>("CurrencyCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DataSource")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EntityStatus")
                        .HasColumnType("int");

                    b.Property<string>("IsoFamilyCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastCardDigits")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProprietaryCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TimeStamp")
                        .HasColumnType("bigint");

                    b.Property<string>("TransactionHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionIdentifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_Transactions_Id");

                    b.HasIndex("AuditInformationId");

                    b.ToTable("Transactions", (string)null);
                });

            modelBuilder.Entity("Airslip.Common.Repository.Types.Entities.BasicAuditInformation", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateDeleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedByUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedByUserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK_AuditInformation_Id");

                    b.ToTable("AuditInformation", (string)null);
                });

            modelBuilder.Entity("Airslip.Analytics.Core.Entities.Account", b =>
                {
                    b.HasOne("Airslip.Common.Repository.Types.Entities.BasicAuditInformation", "AuditInformation")
                        .WithMany()
                        .HasForeignKey("AuditInformationId");

                    b.Navigation("AuditInformation");
                });

            modelBuilder.Entity("Airslip.Analytics.Core.Entities.AccountBalance", b =>
                {
                    b.HasOne("Airslip.Common.Repository.Types.Entities.BasicAuditInformation", "AuditInformation")
                        .WithMany()
                        .HasForeignKey("AuditInformationId");

                    b.Navigation("AuditInformation");
                });

            modelBuilder.Entity("Airslip.Analytics.Core.Entities.AccountBalanceCreditLine", b =>
                {
                    b.HasOne("Airslip.Analytics.Core.Entities.AccountBalanceDetail", null)
                        .WithMany("CreditLines")
                        .HasForeignKey("AccountBalanceDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Airslip.Analytics.Core.Entities.AccountBalanceDetail", b =>
                {
                    b.HasOne("Airslip.Analytics.Core.Entities.AccountBalance", null)
                        .WithMany("Details")
                        .HasForeignKey("AccountBalanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Airslip.Analytics.Core.Entities.Bank", b =>
                {
                    b.HasOne("Airslip.Common.Repository.Types.Entities.BasicAuditInformation", "AuditInformation")
                        .WithMany()
                        .HasForeignKey("AuditInformationId");

                    b.Navigation("AuditInformation");
                });

            modelBuilder.Entity("Airslip.Analytics.Core.Entities.BankCountryCode", b =>
                {
                    b.HasOne("Airslip.Analytics.Core.Entities.Bank", null)
                        .WithMany("CountryCodes")
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Airslip.Analytics.Core.Entities.SyncRequest", b =>
                {
                    b.HasOne("Airslip.Common.Repository.Types.Entities.BasicAuditInformation", "AuditInformation")
                        .WithMany()
                        .HasForeignKey("AuditInformationId");

                    b.Navigation("AuditInformation");
                });

            modelBuilder.Entity("Airslip.Analytics.Core.Entities.Transaction", b =>
                {
                    b.HasOne("Airslip.Common.Repository.Types.Entities.BasicAuditInformation", "AuditInformation")
                        .WithMany()
                        .HasForeignKey("AuditInformationId");

                    b.Navigation("AuditInformation");
                });

            modelBuilder.Entity("Airslip.Analytics.Core.Entities.AccountBalance", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("Airslip.Analytics.Core.Entities.AccountBalanceDetail", b =>
                {
                    b.Navigation("CreditLines");
                });

            modelBuilder.Entity("Airslip.Analytics.Core.Entities.Bank", b =>
                {
                    b.Navigation("CountryCodes");
                });
#pragma warning restore 612, 618
        }
    }
}
